### ISSUE TITLE
Create Demo function template  that takes a processed transaction core event then call stedi mapping and sends output to webhook endpoint

### ISSUE THREAD

**Issue by dejavxtrem** [Stedi-Demos/function-templates#9] opened 2023-06-15 02:18 UTC
Steps
-Get Processed Transaction event from core
-Call stedi mapping to change format
-send stedi mapping output to webhook endpoint

**Comment by rsioss** [comment] 2023-06-27 16:15
Closing as a duplicate of #4

**Closed as not planned by rsioss** 2023-06-27 16:15 UTC
